[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = never
   log file = /var/log/samba/samba.log
   max log size = 1000
   logging = file
   log level = 3

[ebooks]
   path = /libraryit/ebooks
   valid users = @staff, @readonly
   read only = no
   write list = @staff
   create mask = 0664
   directory mask = 0775
   guest ok = no

[papers]
   path = /libraryit/papers
   valid users = @staff, @readonly
   read only = no
   write list = @staff
   create mask = 0664
   directory mask = 0775
   guest ok = no

[sourcecode]
   path = /libraryit/sourcecode
   valid users = @staff
   read only = no
   write list = @staff
   create mask = 0664
   directory mask = 0775
   guest ok = no
   ; Tidak muncul di list untuk non-staff
   browseable = no

[docs]
   path = /libraryit/docs
   valid users = @staff, @readonly
   read only = yes
   write list = librarian
   create mask = 0664
   directory mask = 0775
   guest ok = no
